apiVersion: v1
kind: Service
metadata:
  name: scalable-app-svc
  labels:
    app: scalable-app
spec:
  selector:
    app: scalable-app
  ports:
    - name: http
      port: 80
      targetPort: 8000
  type: ClusterIP