apiVersion: v1
kind: Service
metadata:
  name: scalable-api-svc
  labels:
    app: scalable-api
spec:
  selector:
    app: scalable-api
  ports:
    - name: http
      port: 80
      targetPort: 8000
  type: ClusterIP